apiVersion: v1
kind: Service
metadata:
  name: pr-ci-dashboard
  labels:
    app: pr-ci-dashboard
spec:
  type: ClusterIP
  selector:
    app: pr-ci-dashboard
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
